const properties = [
    {
      id: 1,
      type: "STUDIO",
      title: "Casa Lomas De Machali Machas",
      location: "33 Maple Street, San Francisco, California",
      bedrooms: 3,
      bathrooms: 2,
      size: "600 SqFT",
      price: "$7250,00/SqFT",
      agent: "Arlene McCoy",
      agentImage: "agent1.jpg",
      image: "imagen1.jpg",
    },
    {
      id: 2,
      type: "APARTMENT",
      title: "Villa Del Mar Retreat, Malibu",
      location: "72 Sunset Avenue, Los Angeles, California",
      bedrooms: 2,
      bathrooms: 2,
      size: "600 SqFT",
      price: "$250,00/month",
      agent: "Annette Black",
      agentImage: "agent2.jpg",
      image: "imagen2.jpg",
    },
    {
      id: 3,
      type: "VILLA",
      title: "Rancho Vista Verde, Santa Barbara",
      location: "33 Maple Street, San Francisco, California",
      bedrooms: 4,
      bathrooms: 2,
      size: "600 SqFT",
      price: "$5050,00/SqFT",
      agent: "Ralph Edwards",
      agentImage: "agent3.jpg",
      image: "imagen3.jpg",
    },
    {
      id: 4,
      type: "HOUSE",
      title: "Sunset Heights Estate, Beverly Hills",
      location: "1040 Ocean, Santa Monica, California",
      bedrooms: 3,
      bathrooms: 2,
      size: "600 SqFT",
      price: "$250,00/month",
      agent: "Jacob Jones",
      agentImage: "agent4.jpg",
      image: "imagen4.jpg",
    },
    {
      id: 5,
      type: "OFFICE",
      title: "Coastal Serenity Cottage",
      location: "21 Hillside Drive, Beverly Hills",
      bedrooms: 4,
      bathrooms: 2,
      size: "600 SqFT",
      price: "$7250,00/SqFT",
      agent: "Kathryn Murphy",
      agentImage: "agent5.jpg",
      image: "imagen5.jpg",
    },
    {
      id: 6,
      type: "STUDIO",
      title: "Lakeview Haven, Lake Tahoe",
      location: "8 Broadway, Brooklyn, New York",
      bedrooms: 2,
      bathrooms: 2,
      size: "600 SqFT",
      price: "$250,00/month",
      agent: "Floyd Miles",
      agentImage: "agent6.jpg",
      image: "imagen6.jpg",
    }
  ];
  
  export default properties;
  